core/urls.py
from django.urls import path
from django.contrib.auth.views import  LogoutView

from core.models import GiftCardRequest

from .views import (
    AdminGiftApplicationList,
    AdminGiftApplicationUpdate,
    AdminGiftDetail,
    AdminGiftList,
    AdminNewsCreateView,
    AdminNewsDeleteView,
    AdminNewsDetailView,
    AdminNewsListView,
    AdminReplacementList,
    AdminReplacementUpdate,
    AdminRetirementList,
    AdminRetirementUpdate,
    AdminVacationList,
    AdminVacationUpdate,
    AdminUserUpdate,
    RequestDone,
    UserDashboard,
    UserGiftListView,
    UserGiftRequestChoiceView,
    UserGiftRequestView,
    UserReplacementCreateView,
    UserReplacementDetailView,
    UserRetirementCreationView,
    UserRetirementDetailView,
    UserSearchResult,
    UserShareGiftView,
    UserTransferView,
    UserVacationCreateView,
    index,
    AdminDashboard,
    AdminLoginView,
    AdminUserList,
    AdminUserCreate,
    AdminUserDelete,
    AdminUserDetail,
    admin_logout,
    search_code_status,
    user_logout,
    user_login,
    UserLogoutView,
    UserRetirementView,
    UserReplacementView,
)


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path(
        'SC0gAo/admin/login',
        AdminLoginView.as_view(),
        name='admin_login'
    ),
    path(
        'SC0gAo/admin/dashboard',
        AdminDashboard.as_view(),
        name='admin_dashboard'
    ),
    path(
        'SC0gAo/admin/users',
        AdminUserList.as_view(),
        name='admin_users'
    ),
    path(
        'SC0gAo/admin/user/add',
        AdminUserCreate.as_view(),
        name='admin_user_create'
    ),
    path(
        'SC0gAo/admin/user/remove/<uuid:pk>/',
        AdminUserDelete.as_view(),
        name='admin_user_delete'
    ),
    path(
        'SC0gAo/admin/user/update/<uuid:pk>/',
        AdminUserUpdate.as_view(),
        name='admin_user_update'
    ),
    path(
        'SC0gAo/admin/user/<uuid:pk>/',
        AdminUserDetail.as_view(),
        name='admin_user_detail'
    ),
    path(
        'SC0gAo/admin/replacements/',
        AdminReplacementList.as_view(),
        name='admin_replacements_list'
    ),
    path(
        'SC0gAo/admin/replacements/<uuid:pk>/',
        AdminReplacementUpdate.as_view(),
        name='admin_replacements_update'
    ),
    path(
        'SC0gAo/admin/retirements/',
        AdminRetirementList.as_view(),
        name='admin_retirement_list'
    ),
    path(
        'SC0gAo/admin/retirement/<uuid:pk>/',
        AdminRetirementUpdate.as_view(),
        name='admin_retirement_update'
    ),
    path(
        'SC0gAo/admin/gifts/',
        AdminGiftList.as_view(),
        name='admin_gift_list'
    ),
    path(
        'SC0gAo/admin/gift/<uuid:pk>/',
        AdminGiftDetail.as_view(),
        name='admin_gift_detail'
    ),
    path(
        'SC0gAo/admin/logout',
        admin_logout,
        name='admin_logout'
    ),
    path(
        'SC0gAo/admin/vacation/list',
        AdminVacationList.as_view(),
        name='admin_vacation_list'
    ),
    path(
        'SC0gAo/admin/vacation/<uuid:pk>/',
        AdminVacationUpdate.as_view(),
        name='admin_vacation_update'
    ),
    path(
        'SC0gAo/admin/card/requests/',
        AdminGiftApplicationList.as_view(),
        name='admin_card_requests_list'
    ),
    path(
        'SC0gAo/admin/card/requests/<uuid:pk>/',
        AdminGiftApplicationUpdate.as_view(),
        name='admin_card_requests_update'
    ),
    path(
        'SC0gAo/admin/news/',
        AdminNewsListView.as_view(),
        name='admin_card_news_list'
    ),
    path(
        'SC0gAo/admin/news/create',
        AdminNewsCreateView.as_view(),
        name='admin_card_news_create'
    ),
    path(
        'SC0gAo/admin/news/detail/<uuid:pk>/',
        AdminNewsDetailView.as_view(),
        name='admin_card_news_detail'
    ),
    path(
        'SC0gAo/admin/news/delete/<uuid:pk>/',
        AdminNewsDeleteView.as_view(),
        name='admin_card_news_delete'
    ),

    # -----------------------------------------
    # -----[ User Links ] ---------------------
    # -----------------------------------------
    
    path(
        'login/',
        user_login,
        name='user_login'
    ),
    path(
        'logout/',
        user_logout,
        name='user_logout'
    ),
    path(
        'dashboard/',
        UserDashboard.as_view(),
        name='user_dashboard'
    ),
    path(
        'logout',
        UserLogoutView.as_view(),
        name='user_logout'
    ),
    # ---------------------------------------
    # ----------------[ Retirement ] --------
    # ---------------------------------------
    path(
        'retirement',
        UserRetirementView.as_view(),
        name='user_retirement'
    ),
    path(
        'retirement/create/',
        UserRetirementCreationView.as_view(),
        name='user_retirement_create'
    ),
    path(
        'retirement/detail/<uuid:pk>/',
        UserRetirementDetailView.as_view(),
        name='user_retirement_detail'
    ),
    # ---------------------------------------
    # ----------------[ Replacement ] -------
    # ---------------------------------------
    path(
        'replacement',
        UserReplacementView.as_view(),
        name='user_replacement'
    ),
    path(
        'replacement/create/',
        UserReplacementCreateView.as_view(),
        name='user_replacement_create'
    ),
    path(
        'replacement/detail/<uuid:pk>/',
        UserReplacementDetailView.as_view(),
        name='user_replacement_detail'
    ),
    # ---------------------------------------
    # ----------------[ Transfer ] ----------
    # ---------------------------------------
    path(
        'transfer',
        UserTransferView.as_view(),
        name='user_transfer'
    ),

    # ---------------------------------------
    # ----------------[ Gift Card ] ---------
    # ---------------------------------------
    path(
        'gift/list/',
        UserGiftListView.as_view(),
        name='user_git_list'
    ),
    path(
        'gift/share/',
        UserShareGiftView.as_view(),
        name='user_git_share'
    ),
    path(
        'gift/detail/<uuid:pk>?',
        UserReplacementDetailView.as_view(),
        name='user_git_detail'
    ),
    path(
        'search/',
        UserSearchResult.as_view(),
        name='user_search'
    ),
    path(
        'request/done/',
        RequestDone.as_view(),
        name='request_done'
    ),
    path(
        'request/check/',
        search_code_status,
        name='request_check'
    ),
    path(
        'request/vacation/',
        UserVacationCreateView.as_view(),
        name='request_vacation'
    ),
    path(
        'request/card/order/<str:amount>/',
        UserGiftRequestView.as_view(),
        name='request_card_order'
    ),
    path(
        'request/card/choice/',
        UserGiftRequestChoiceView.as_view(),
        name='request_card_choice'
    ),
]

usforces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('_/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from ast import Dict
from http.client import HTTPResponse
import json
from traceback import extract_tb
from typing import Any
from django.forms import BaseModelForm

from django.http import HttpResponse
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404, render
from django.views.generic import (
    TemplateView,
    DetailView,
    DeleteView,
    CreateView,
    ListView,
    UpdateView,
    View
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.shortcuts import redirect, resolve_url
from django.core import serializers

from core.forms import (
    CheckStatusForm,
    CustomUserCreationForm,
    GiftCardRequestForm,
    GiftCreationForm,
    NewsCreationForm,
    ReplacementForm,
    RetirementForm,
    UserCreationForm,
    UserLoginForm,
    VacationForm,
    AdminUserUpdateForm
)

from core.models import Gift, GiftCardRequest, News, Replacement, Retirement, User, Vacation
from core.utils import get_random_string


def index(request):
    template_name = 'core/index.html'
    context = {'news': News.objects.all()[:4]}
    if request.session.has_key('CATEGORY_ID') and request.session.has_key('CATEGORY_NAME'):
        del request.session['CATEGORY_ID']
        del request.session['CATEGORY_NAME']
    return render(request, template_name, context)


def search_code_status(request):
    template_name = "core/request_check_status.html"
    context = {'form': CheckStatusForm, "obj": ""}

    if request.method == "POST":

        if (form := CheckStatusForm(request.POST)).is_valid():
            code = request.POST.get('code', None).strip()
            category = request.POST.get('category', None)

            if (code and category) is None:
                pass

            match(category):
                case "replacement":
                    try:
                        obj = Replacement.objects.get(id=code)
                        return render(request, template_name, context={'form': form, 'obj': obj})
                    except Replacement.DoesNotExist:
                        return render(request, template_name, context={'form': form, 'obj': None})

                case "retirement":
                    try:
                        obj = Retirement.objects.get(id=code)
                        return render(request, template_name, context={'form': form, 'obj': obj})
                    except Retirement.DoesNotExist:
                        return render(request, template_name, context={'form': form, 'obj': None})

                case "vacation":
                    try:
                        obj = Vacation.objects.get(id=code)
                        return render(request, template_name, context={'form': form, 'obj': obj})
                    except Vacation.DoesNotExist:
                        return render(request, template_name, context={'form': form, 'obj': None})

                case "card_purchase":
                    try:
                        obj = GiftCardRequest.objects.get(id=code)
                        return render(request, template_name, context={'form': form, 'obj': obj})
                    except GiftCardRequest.DoesNotExist:
                        return render(request, template_name, context={'form': form, 'obj': None})

    return render(request, template_name, context)


# ---------------------------------------------------------
# ----------------- [ Admin User Section ] ----------------
# ---------------------------------------------------------
class AdminLoginView(LoginView):
    template_name = 'core/admin_login.html'

    def post(self, request, *args, **kwargs) -> HTTPResponse:
        try:
            email = request.POST.get('username', None)
            password = request.POST.get('password', None)

            user = User.objects.get(email=email)
            if (user := authenticate(request, email=email, password=password)) is None:
                context = {
                    'error': 'Access denied'
                }
                return render(request, self.template_name)
            login(request, user)

        except User.DoesNotExist as e:
            context = {
                'error': 'No user with this details'
            }
            return render(request, self.template_name, context)
        return super().post(request, *args, **kwargs)


def admin_logout(request):
    logout(request)
    return redirect('core:admin_login')


class AdminDashboard(LoginRequiredMixin, TemplateView):
    template_name = 'core/admin_dashboard.html'
    extra_context = {
        'users': User.objects.all(),
        'replacements': Replacement.objects.all(),
        'gifts': Gift.objects.all(),
        'retirement': Retirement.objects.all()
    }


class AdminUserList(LoginRequiredMixin, ListView):
    context_object_name = 'users'
    template_name = 'core/admin_list_user.html'

    def get_queryset(self):
        return User.objects.exclude(email='admin@gmail.com')


class AdminUserUpdate(LoginRequiredMixin, UpdateView):
    context_object_name = 'users'
    template_name = 'core/admin_dashboard_add_user.html'
    model = User
    form_class = AdminUserUpdateForm

    def get_success_url(self) -> str:
        return resolve_url('core:admin_user_detail', pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_type'] = 'update'
        return context


class AdminUserCreate(LoginRequiredMixin, CreateView):
    template_name = 'core/admin_dashboard_add_user.html'
    model = User
    success_url = reverse_lazy('core:admin_users')
    form_class = CustomUserCreationForm

    def form_valid(self, form) -> HTTPResponse:
        form.instance.role = 'client'
        form.instance.username = '{0}_{1}'.format(
            form.cleaned_data.get('username'),
            get_random_string(8)
        )
        return super().form_valid(form)

class AdminUserDelete(LoginRequiredMixin, DeleteView):
    model = User
    template_name = "core/admin_user_delete.html"
    success_url = reverse_lazy('core:admin_users')
    context_object_name = 'user'


class AdminUserDetail(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'core/admin_user_detail.html'
    context_object_name = 'user'


class AdminUpdateSolider(LoginRequiredMixin):
    pass


class AdminReplacementList(ListView):
    model = Replacement
    context_object_name = 'replacements'
    template_name = "core/admin_list_replacements.html"


class AdminReplacementUpdate(View):
    def get(self, *args, **kwargs):
        obj = get_object_or_404(Replacement, pk=self.kwargs.get('pk'))
        obj.is_approved = True
        obj.save()
        return redirect('core:admin_replacements_list')


class AdminRetirementList(ListView):
    model = Retirement
    context_object_name = 'retirements'
    template_name = "core/admin_list_retire.html"


class AdminRetirementUpdate(View):
    def get(self, *args, **kwargs):
        obj = get_object_or_404(Retirement, pk=self.kwargs.get('pk'))
        obj.is_approved = True
        obj.save()
        return redirect('core:admin_retirement_list')


class AdminGiftList(ListView):
    model = Gift
    context_object_name = 'gifts'
    template_name = "core/admin_list_gifts.html"


class AdminGiftDetail(DetailView):
    model = Gift
    context_object_name = 'card'
    template_name = "core/admin_detail_gift.html"


class AdminGiftApplicationList(ListView):
    model = GiftCardRequest
    context_object_name = 'gifts'
    template_name = "core/admin_list_gift_order.html"


class AdminGiftApplicationUpdate(View):
    def get(self, *args, **kwargs):
        obj = get_object_or_404(GiftCardRequest, pk=self.kwargs.get('pk'))
        obj.is_approved = True
        obj.save()
        return redirect('core:admin_card_requests_list')


class AdminVacationList(ListView):
    model = Vacation
    context_object_name = 'vacations'
    template_name = "core/admin_list_vacation.html"


class AdminVacationUpdate(View):
    def get(self, *args, **kwargs):
        obj = get_object_or_404(Vacation, pk=self.kwargs.get('pk'))
        obj.is_approved = True
        obj.save()
        return redirect('core:admin_vacation_list')


class AdminNewsListView(ListView):
    model = News
    context_object_name = 'news'
    template_name = "core/admin_list_news.html"


class AdminNewsCreateView(CreateView):
    model = News
    template_name = "core/admin_news_create.html"
    success_url = reverse_lazy("core:admin_card_news_list")
    form_class = NewsCreationForm


class AdminNewsDetailView(DetailView):
    model = News
    template_name = "core/admin_news_detail.html"
    context_object_name = "news"


class AdminNewsDeleteView(View):
    def get(self, *args, **kwargs):
        News.objects.get(pk=self.kwargs.get('pk')).delete()
        return redirect('core:admin_card_news_list')
# ---------------------------------------------------------
# ----------------- [User Section ] ---------------------
# ---------------------------------------------------------


def user_logout(request):
    logout(request)
    return redirect('core:index')


class UserLogoutView(View):
    def get(self, *args, **kwargs):
        self.request.session.flush()
        return redirect('core:user_login')


def user_login(request):
    template_name = 'core/index.html'
    context = {"form": UserLoginForm()}

    if request.method == "POST":
        if not (login_form := UserLoginForm(request.POST)).is_valid():
            return render(request, template_name=template_name)

        try:
            # military_id  = request.POST.get('military_id', None)
            military_id = request.POST.get('military_id', None)

templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% block head_content %}{% endblock head_content %} {% block title %}
    <title>USFORCES</title>
    {% endblock %}

    <!-- links -->
    <link
      rel="stylesheet"
      href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}"
    />
  </head>
  <body>
    <div id="ytWidget"></div>

    {% block content %}{% endblock content %}
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
      var Tawk_API = Tawk_API || {},
        Tawk_LoadStart = new Date();
      (function () {
        var s1 = document.createElement("script"),
          s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = "https://embed.tawk.to/63446e2437898912e96de41a/1gf1ksh3j";
        s1.charset = "UTF-8";
        s1.setAttribute("crossorigin", "*");
        s0.parentNode.insertBefore(s1, s0);
      })();
    </script>
    <!--End of Tawk.to Script-->

    <!-- Translate -->
    <script
      src="https://translate.yandex.net/website-widget/v1/widget.js?widgetId=ytWidget&pageLang=en&widgetTheme=light&autoMode=true"
      type="text/javascript"
    ></script>
    <!-- End translate -->

    <script src="{% static 'vendors/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/splide/dist/js/splide.min.js' %}"></script>
    {% block js_block %}{% endblock js_block %}
  </body>
</html>

templates/core/user_gift_create.html
{% extends 'core/user_dashboard.html' %} 
{% load static %} 
{% load widget_tweaks %}


{% block admin_head %}
<style>
    a{
        text-decoration: none !important;
    }
</style>
{% endblock admin_head %}


{% block main%}
<div class="content-body">
  <div class="row page-titles mx-0">
    <div class="col p-md-0">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:user_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'core:user_replacement' %}">Replacements</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'core:user_replacement_create' %}">Application</a></li>
        </ol>
    </div>
  </div>
  <!-- row -->
  
  <div class="container-fluid">
    <!-- 
          ***************************************
          ADD SOLIDER BUTTON
          ***************************************
       -->
    <section class="my-2 d-flex justify-content-start">
      <a
        href="{% url 'core:user_replacement' %}"
        class="btn mb-1 btn-primary text-light"
      >
        <span>Back</span>
      </a>
    </section>
  
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3>Gift</h3>
          </div>
          <div class="card-body">
            <div class="form-validation">
              {% if form.errors %}
                {% for err in form.errors %}
                  <small class="text-danger">{{ err }}</small>
                {% endfor %}
              {% endif %}
              <form class="form-valide" method="post" enctype="multipart/form-data">
                  {% csrf_token %}

                <div class="form-group row">
                  <label class="col-lg-4 col-form-label" for="val-username"
                    >{{ form.solder_first_name.label_tag }} <span class="text-danger">*</span>
                  </label>
                  <div class="col-lg-6">
                      {{   form.solder_first_name|attr:"class:form-control"|attr:"placeholder:Enter solider first name id"|attr:"type:text" }}
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-lg-4 col-form-label" for="val-username"
                    >{{ form.solder_last_name.label_tag }} <span class="text-danger">*</span>
                  </label>
                  <div class="col-lg-6">
                      {{   form.solder_last_name|attr:"class:form-control"|attr:"placeholder:Enter solider last name"|attr:"type:text" }}
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-lg-4 col-form-label" for="val-username"
                    >{{ form.solders_id_number.label_tag }} <span class="text-danger">*</span>
                  </label>
                  <div class="col-lg-6">
                      {{   form.solders_id_number|attr:"class:form-control"|attr:"placeholder:Enter solider military id"|attr:"type:text" }}
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-lg-4 col-form-label" for="val-username"
                    >{{ form.gift_image.label_tag }} <span class="text-danger">*</span>
                  </label>
                  <div class="col-lg-6">
                      {{   form.gift_image|attr:"class:form-control"|attr:"type:file"|attr:'accept:image/png, image/jpeg, image/jpg' }}
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-lg-4 col-form-label" for="val-username"
                    >{{ form.git_card_number.label_tag }} <span class="text-danger">*</span>
                  </label>
                  <div class="col-lg-6">
                      {{   form.git_card_number|attr:"class:form-control"|attr:"type:text" }}
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-lg-4 col-form-label" for="val-username"
                    >{{ form.gift_card_amount.label_tag }} <span class="text-danger">*</span>
                  </label>
                  <div class="col-lg-6">
                      {{   form.gift_card_amount|attr:"class:form-control"|attr:"type:text" }}
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-lg-4 col-form-label" for="val-username"
                    >{{ form.gift_card_type.label_tag }} <span class="text-danger">*</span>
                  </label>
                  <div class="col-lg-6">
                      {{   form.gift_card_type|attr:"class:form-control"|attr:"placeholder:Enter your name" }}
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-lg-8 ml-auto">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


{% endblock main %}

templates/core/user_gift_detail.html
{% extends 'core/admin_dashboard_base.html' %} {% load static %} 


{% block admin_head %}
<style>
    a{
        text-decoration: none !important;
    }
</style>
{% endblock admin_head %}


{% load widget_tweaks %} {% block main%}
<div class="content-body">
  <div class="row page-titles mx-0">
    <div class="col p-md-0">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'core:user_dashboard' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">
          <a href="{% url 'core:user_replacement' %}">Replacements</a>
        </li>
        <li class="breadcrumb-item active">
          <a href="{% url 'core:user_replacement_create' %}">Application</a>
        </li>
      </ol>
    </div>
  </div>
  <!-- row -->

  <div class="container-fluid">
    <!-- 
          ***************************************
          ADD SOLIDER BUTTON
          ***************************************
       -->
    <section class="my-2 d-flex justify-content-start">
      <a
        href="{% url 'core:user_git_list' %}"
        class="btn mb-1 btn-primary text-light"
      >
        <span>Back</span>
      </a>
    </section>

    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="card-header">
          <h4 class="card-title">Gift Detail</h4>
        </div>
        <div class="card-body">
          <div class="basic-form">

            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Solider Name</label>
              <div class="col-sm-9">
                <input
                  type="text"
                  readonly="readonly"
                  class="form-control-plaintext"
                  value="{{ gift.solder_first_name }} {{ gift.solder_last_name }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Solider Card Number</label>
              <div class="col-sm-9">
                <input
                  type="text"
                  readonly="readonly"
                  class="form-control-plaintext"
                  value="{{ gift.git_card_number }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Gift Card Amount</label>
              <div class="col-sm-9">
                <input
                  type="text"
                  readonly="readonly"
                  class="form-control-plaintext"
                  value="{{ gift.gift_card_amount }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Gift Card Type</label>
              <div class="col-sm-9">
                <input
                  type="text"
                  readonly="readonly"
                  class="form-control-plaintext"
                  value="{{ gift.gift_card_type }}"
                />
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Gift Image</label>
              <div class="col-sm-9">
               <img src="{{ gift.gift_image.url }}" alt="">
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock main %}

templates/core/user_replacement.html
{% extends 'core/user_dashboard.html' %} 
{% load static %} 


{% block admin_head %}
<link href="{% static 'plugins/sweetalert/css/sweetalert.css' %}" rel="stylesheet">
<style>
    a{
        text-decoration: none !important;
    }
</style>
{% endblock admin_head %}

{% block main%}
<div class="content-body">
  <div class="container-fluid mt-3">
    <!-- 
          ***************************************
          ADD SOLIDER BUTTON
          ***************************************
       -->
       <div class="section my-2 d-flex justify-content-end">
          <a href="{% url 'core:user_replacement_create' %}" class="btn mb-1 btn-primary text-light">
              <span>Apply for replacement</span>
          </a>
       </div>
    <!-- 
          ***************************************
          USER liSTS
          ***************************************
       -->
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <div class="card-title">
              <h4>Replacement Applications({{replacements.count}})</h4>
            </div>
            <div class="active-member">
              <div class="table-responsive">
                <table class="table table-xs mb-0">
                  <thead>
                    <tr>
                      <!-- <th>S/N</th> -->
                      <th>ID</th>
                      <th>Replace</th>
                      <th>Date</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for obj in replacements %}
                    <tr>
                      <td>{{ obj.pk }}</td>
                      <td>{{ obj.name_of_soldier }}</td>
                      <td>
                        <span>{{ obj.timestamp  }}</span>
                      </td>
                      <td>
                        {% if obj.status == 'pending' %}
                        <span class="text-warning">{{ obj.status }}</span>
                        {% elif obj.status == 'declined' %}
                        <span class="text-danger}">{{ obj.status }}</span>
                        {% elif obj.status == 'approved' %}
                        <span class="text-sucess">{{ obj.status }}</span>
                        {% endif %}
                      </td>
                      <td>
                        <span class="d-flex">
                          <a
                            href="{% url 'core:user_replacement_detail' obj.pk %}"
                            data-toggle="tooltip"
                            data-placement="top"
                            title="Edit"
                            class="nav-link"
                          >
                            <i class="fa fa-pencil color-muted m-r-5"></i>
                          </a>
                        </span>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- #/ container -->
{% endblock main %}


{% block admin_script %}

<script src="{% static 'plugins/sweetalert/js/sweetalert.init.js' %}"></script>
<script src="{% static 'plugins/common/common.min.js' %}"></script>
<script src="{% static 'js/custom.min.js' %}"></script>
<script src="{% static 'js/settings.js' %}"></script>
<script src="{% static 'js/gleek.js' %}"></script>
<script src="{% static 'js/styleSwitcher.js' %}"></script>


<script src="{% static 'plugins/sweetalert/js/sweetalert.min.js' %}"></script>

{% endblock admin_script %}